### ISSUE TITLE
Make test size a keyword argument

### ISSUE THREAD

**Issue by pmcarpan** [Ritam-Guha/Py_FS#20]
In many of the algorithms, something similar to the below line has been used to split the data into two partitions.

```
train_test_split(train_data, train_label, stratify=train_label, test_size=0.2)
```

I am suggesting, instead of keeping the `test_size` parameter fixed to `0.2`, a keyword argument can be added with a default value of `0.2`. This would allow users to pass in custom values if they want while keeping a suitable default value.

_Note: Please close this issue if I am mistaken._

**Comment by Ritam-Guha** [comment]
Thanks a lot for your recommendation. We will take care of it and let you know about the update.

**Comment by Ritam-Guha** [comment]
Hi @pmcarpan, I have changed the code and now a prompt will appear while running the code asking the user to enter the validation percentage. Sorry for the delay. Thanks a lot for your patience. 🙂
