### ISSUE TITLE
Number of Features

### ISSUE THREAD

**Issue by frknblcn** [Ritam-Guha/Py_FS#22]
Hi Guha
I want to use wrapper feature selection methods. My data  consists of 200 features and I want to select the best 20 features. Is it available to select the max feature number in your code?

**Comment by Rohit-Kundu** [comment]
No. Wrapper based methods select the optimal feature subset using a learning algorithm in its crux. They don't give scores/ranks to assert feature importance. You can use the filter methods to select a specified number of features, but wrapper algorithms cannot do that.
