### ISSUE TITLE
Metrics Related

### ISSUE THREAD

**Issue by rishavpramanik** [Ritam-Guha/Py_FS#26]
The default  weights for evaluation is set at micro if this can be customised according to user inputs by adding an argument, it would have been much better

**Comment by Ritam-Guha** [comment]
Hey,
I'm sorry for the inconvenience. But have you tried the latest version? It generates a prompt for user-specified weights.
Please let me know if you face any problems.

Thanks,
Ritam

**Comment by rishavpramanik** [comment]
Yes, thanks for the update, I would take a moment to appreciate your and your team effort
