### ISSUE TITLE
Regarding Filter method

### ISSUE THREAD

**Issue by akshitamishra1213** [Ritam-Guha/Py_FS#30]
Hello There, 
I am a bit new to all these python things but thanks to your wonderful code I am getting a bit of confidence. 
I tried to use Filter method Pearson Correlation Coefficient. Got feature ranks and all. 
 But I couldn't understand how to prepare my dataset with the selected best features. 
If you could please guide.

**Comment by akshitamishra1213** [comment]
or can you give a demo of how to read a dataset use one of these filters and create improved dataset plzzz

**Comment by Ritam-Guha** [comment]
So, we have an API to do that.
If you go to the Google Colab page for the demonstration: https://colab.research.google.com/drive/1PafNTmVgWv9Qz6j7bI41XqPT6CCCIb1T?usp=sharing#scrollTo=RJhTgmqhienI,
You will find that we are printing something called `solution.ranked_features` for the filter part. 
That basically represents your features in ranked order. That means the first column for that matrix represents the best features according to our process.
If you want to use like 10 features, then you can just get the features like `solution.ranked_features[:, :10]`.

**Comment by akshitamishra1213** [comment]
Thank you for Quick response. :)
