### ISSUE TITLE
LICENSE text

### ISSUE THREAD

**Issue by firefly-cpp** [Ritam-Guha/Py_FS#32]
It seems that copyright notice is not correct. Please check your license text.

"Copyright (c) 2010-2020 Google, Inc. http://angularjs.org"

**Comment by Ritam-Guha** [comment]
Hey, 
This MIT license is auto generated by Github. I am not exactly sure what you mean by copyright notice being incorrect. Can you please elaborate on this?

**Comment by firefly-cpp** [comment]
@Ritam-Guha, copyright holder name is probably incorrect. You are the copyright holder.

**Comment by Ritam-Guha** [comment]
Oh @firefly-cpp , yeah. Thanks a lot for that. I don't know much about Licensing. So, I think I overlooked it 😅.
Thanks. 😃
